name : first Congifuration of Github Action workflow.

# events
on :
  push: 
    branches : [ main ]
  pull_request:
    branches : [ main ]
    
# A workflow run is made up of one or more jobs that can run
sequentially or in parallel
jobs :
# This workflow contains a single job called "build"
  build : 
    # The type of runner that the job will run on
    runs-on : ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses : actions/checkout@v2

      # Runs a single command using the runners shell
      - name: run a one-line script
        run: echo Hello, world!
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: 
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Cache node modules
        uses: actions/cache@v2
        env: 
          cache-name: cache-node-modules
        with: 
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-key: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.6
      with:
        # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: build
        # The desired behavior if no files are found using the provided path.
      Available Options:
        warn: Output a warning but do not fail the action
    
        if-no-files-found: warn
        
        # Duration after which artifact will expire in days. 0 means using default retention. Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
        retention-days: 0
        
        # The level of compression for Zlib to be applied to the artifact archive. The value can range from 0 to 9: - 0: No compression - 1: Best speed - 6: Default compression (same as GNU Gzip) - 9: Best compression Higher levels will result in better compression, but will take longer to complete. For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.
          
        -name: Install Dependencies
         run: npm install
        -name: Build
         run: npm build
        -name: Test
         run: npm test 

  
